name: demo_workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'push.json'
  workflow_dispatch:
    inputs:
      input1:
        description: sample input1
        type: string
        required: true
      input2: 
        description: sample input2
        type: string
        required: true
      environment:
        description: "Cloud environment" 
        type: choice
        required: true
        default: dev
        options: ['dev','test', 'prod']
jobs:
  echo_something:
    name: echo_${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Set current date as env variable
        run: TZ=IST && echo "WORKFLOW_DATE_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo WORKFLOW_DATE_TIME
        run: echo "${{ env.WORKFLOW_DATE_TIME }}"
      - name: echo actor
        run: echo ${{ github.actor }}
      - name: echo event name
        run: echo ${{ github.event_name	}}
      - name: echo file at event path
        run: cat ${{ github.event_path }}
      - name: check jq
        run: jq .inputs ${{ github.event_path }}
      - name: Create JSON Object
        run: | 
          jq -n \
          --arg workflow "${{ github.workflow }}" \
          --arg actor "${{ github.actor }}" \
          --arg event_name "${{ github.event_name }}" \
          --arg WORKFLOW_DATE_TIME "${{ env.WORKFLOW_DATE_TIME }}" \
          --argjson inputs "$(jq .inputs ${{ github.event_path }})" \
          '$ARGS.named'