name: demo_workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'push.json'
  workflow_dispatch:
    inputs:
      input1:
        description: sample input1
        type: string
        required: true
      input2: 
        description: sample input2
        type: string
        required: true
      environment:
        description: "Cloud environment" 
        type: choice
        required: true
        default: dev
        options: ['dev','test', 'prod']
jobs:
  echo_something:
    name: echo_${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set and echo
        run: | 
          echo "WORKFLOW_DATE_TIME=$(TZ=":Asia/Calcutta" date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo "${{ env.WORKFLOW_DATE_TIME }}"
          echo ${{ github.actor }}
          echo ${{ github.event_name }}
          jq .inputs ${{ github.event_path }}
          jq -n \
          --arg workflow "${{ github.workflow }}" \
          --arg actor "${{ github.actor }}" \
          --arg event_name "${{ github.event_name }}" \
          --arg WORKFLOW_DATE_TIME "${{ env.WORKFLOW_DATE_TIME }}" \
          --argjson inputs "$(jq .inputs ${{ github.event_path }})" \
          '$ARGS.named'
      - name: Update status markdown
        run: |
          echo "| ${{ github.workflow }} | ${{ github.event_name }} | ${{ github.actor }} | $(jq .inputs ${{ github.event_path }}) | $(TZ=":Asia/Calcutta" date +'%Y-%m-%dT%H:%M:%S') ||"